# Generated by Django 5.1.1 on 2024-10-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
