# Generated by Django 5.1.1 on 2024-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(default='default-uid', max_length=255, unique=True),
        ),
    ]
