# Generated by Django 5.1.1 on 2024-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
