# Generated by Django 5.1.1 on 2024-10-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhd',
            name='avoidDelayingThoughtIntensiveTasks',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='difficultyConcentratingOnDirectSpeech',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='difficultyGettingOrganized',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='difficultyKeepingAttention',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='feelOverlyActiveCompelled',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='fidgetOrSquirmWhenSitting',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='makeCarelessMistakes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='misplaceOrDifficultyFindingThings',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='problemsRememberingAppointments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='troubleWrappingUpFinalDetails',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
