# Generated by Django 5.1.1 on 2024-10-26 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_adhd_avoiddelayingthoughtintensivetasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhd',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
