# Generated by Django 5.1.1 on 2024-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bdi_created_at_enneagram_created_at_gad_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enneagram',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ibt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mdq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='npq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ocir',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='gad',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ocir',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
