# Generated by Django 5.1.1 on 2024-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_diagnosis_userquestionnaire_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFTQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('talksALot', models.IntegerField()),
                ('noticesWeakPoints', models.IntegerField()),
                ('doesThingsCarefully', models.IntegerField()),
                ('isSadDepressed', models.IntegerField()),
                ('isOriginal', models.IntegerField()),
                ('keepsThoughtsToThemselves', models.IntegerField()),
                ('isHelpfulNotSelfish', models.IntegerField()),
                ('isCareless', models.IntegerField()),
                ('isRelaxed', models.IntegerField()),
                ('isCurious', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
