# Generated by Django 5.1.1 on 2024-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bftquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPI2Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rarelyWorryAboutHealth', models.BooleanField(default=False)),
                ('alwaysTellTruth', models.BooleanField(default=False)),
                ('feelTiredMostOfTheTime', models.BooleanField(default=False)),
                ('feelPunishedWithoutCause', models.BooleanField(default=False)),
                ('botheredByUpsetStomach', models.BooleanField(default=False)),
                ('getLotOfHeadaches', models.BooleanField(default=False)),
                ('likeToArrangeFlowers', models.BooleanField(default=False)),
                ('someoneHasItInForMe', models.BooleanField(default=False)),
                ('oftenDisturbingThoughts', models.BooleanField(default=False)),
                ('hearThingsOthersCantHear', models.BooleanField(default=False)),
                ('amHappierThanMostPeople', models.BooleanField(default=False)),
                ('amEasilyEmbarrassed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
