# Generated by Django 5.1.1 on 2024-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_adhd_bdi_enneagram_gad_ibt_mdq_npq_ocir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='doesThingsCarefully',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='isCareless',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='isCurious',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='isHelpfulNotSelfish',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='isOriginal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='isRelaxed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='isSadDepressed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='keepsThoughtsToThemselves',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='noticesWeakPoints',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bftquestionnaire',
            name='talksALot',
            field=models.CharField(max_length=100),
        ),
    ]
